---
name: Update Docker Hub description

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: peter-evans/dockerhub-description@v4
        with:
          username: yusoltsev
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: yusoltsev/protoc
